DestinE-Climate-DT/AQUA

CHANGELOG.md
diagnostics/tropical_rainfall/cli/cli_config_trop_rainfall.yml

As per title, updates the paths according to https://earth.bsc.es/gitlab/digital-twins/de_340-2/project_management/-/issues/519#note_342496

[OP] Update observation dataset paths in tropical rainfall CLI configuration

---

CHANGELOG.md
config/diagnostics/ecmean/interface/interface_AQUA_climatedt.yaml

Cherry picking commit from #1696

[OP] Fix net surface radiative flux and wind stresses in ecmean 

---

CHANGELOG.md
cli/aqua-web/push_s3.py

 [OP] Hotfix: push_s3 compatibility with boto3>=1.36.0

---

.readthedocs.yaml
CHANGELOG.md

This introducing the required readthedocs changes to activate the automatic workflow
Close #1694
----

prepare readthedocs file

---

CHANGELOG.md
README.md

As per title
Close #issue_number

readme and badge for documentation

---

.readthedocs.yaml
README.md

This PRs is a tentative cherry-pick to provide of readthedocs build also the `v013-operational` branch.

Docs for operations

---

.github/workflows/aqua-complete.yml
diagnostics/ocean3d/ocean3d/ocean_circulation/mld.py

Improve the monthly action to include all the tests and fix a linting issue that was preventing running the monthly test matrix
Close #1707

Fix monthly test

---

CHANGELOG.md
config/catgen/production.j2
config/catgen/reduced.j2
docs/sphinx/source/adding_data.rst
src/aqua/gsv/intake_gsv.py
src/aqua/gsv/timeutil.py
templates/catgen/config.tmpl
tests/catgen/fdb_info_file.yaml
tests/test_gsv.py

[v0.14] Fdb from file

---

.github/ISSUE_TEMPLATE/01-bug-report.yml

As per title, since the file used to create the issue template is the one in the main

Update 01-bug-report.yml for v0.13.2

---

.github/workflows/aqua.yml
CHANGELOG.md
README.md
codecov.yml

This update the coverage file to have a complete coverage report on coveralls 
Also include DOI badge in the Readme
Close #1695 #1722 
----

Codecov extensions and badge

---

CHANGELOG.md
config/catgen/production.j2
config/catgen/reduced.j2

Replicate #1742 
Close  #1740
----

Changing if statement for fixer_name in catgen

---

CHANGELOG.md
cli/aqua-analysis/aqua-analysis.py
cli/aqua-analysis/config.aqua-analysis.yaml

Revert the AQUA_CONFIG definition to the original meaning
Close #1751

[OP] aqua analysis bugfix

---

CHANGELOG.md
cli/aqua-analysis/aqua-analysis.py
cli/aqua-analysis/config.aqua-analysis.yaml

bugfix AQUA paths for diagnostics config

---

CHANGELOG.md
src/aqua/reader/reader.py
tests/test_basic.py

update xr.Dataset generated from the reader with the metadata of exp, model, source and catalog. This metadata appending happens for each variable. 
Close #1678
----

add metadata to each dataset

---

CHANGELOG.md
pyproject.toml

Remove some files from coverage count. @mnurisso anything else that is worth to be ignored?

remove worthless blocks from coverage

---

config/grids/observations.yaml

enable EN4 regrid

---

CHANGELOG.md
docs/sphinx/source/adding_data.rst
src/aqua/gsv/intake_gsv.py
tests/catgen/fdb_info_hpc-only.yaml
tests/test_gsv.py

Main version of #1761 
Close #1760

Intake GSV can now handle fdb_info_file with only the data block

---

config/grids/tests.yaml

As per title, necessary for #1701

Add new grid defintion for hpz3 nested FESOM grid

---

CHANGELOG.md
cli/hpc2020-install/hpc2020_install.sh
docs/sphinx/source/installation.rst

This PR adds documentation and an installation script  to use efficiently AQUA on HPC2020 at ECMWF.

Installation of AQUA on ECMWF HPC2020

---

CHANGELOG.md
environment.yml
pyproject.toml

Update zarr dependency to allow versions >=3.0.0

---

CHANGELOG.md
docs/sphinx/source/diagnostics/guidelines/class_structure.rst
docs/sphinx/source/diagnostics/guidelines/default_parser.rst
docs/sphinx/source/diagnostics/guidelines/output_management.rst
docs/sphinx/source/diagnostics/index.rst
docs/sphinx/source/other_components.rst
src/aqua/reader/reader.py
tests/test_basic.py

Following the decision taken in #1776 I've updated the already existing attributes added by AQUA and added the version as required in #1772 
Close #1776

Update AQUA attributes standard aspect

---

.github/workflows/aqua.yml

Add condition for action for workflow dispatch and schedule

---

config/fixes/tests.yaml
config/grids/tests.yaml

Updating grid for FESOM hpz3 test source in order to enable ocean3d tests under development in #1780

Update test-hpz3-nested-fesom-3d configuration in tests.yaml 

---

src/aqua_diagnostics/core/diagnostic.py

In diagnostic class initialisation, pass information on the loglevel
Close #1804
----

pass loglevel info for diag

---

CHANGELOG.md
config/fixes/convention-eccodes.yaml

As noticed in #1798 a wrong grib code was used for tcc.
Here we fix the issue for the operational branch
Close #1798 for the operational cycle

[OP] correct tcc target grib code

---

CHANGELOG.md
pyproject.toml

Update of GSV to 2.9.6 for the operational release

[OP] GSV update to 2.9.6

---

CHANGELOG.md
diagnostics/ocean3d/cli/cli_ocean3d.py

This addresses a bug in `cli_ocean3d.py` discussed in #1810 
Close #1810
----

Fix cli_ocean3d regridding of observations

---

.github/workflows/aqua.yml
CHANGELOG.md
codecov.yml
pyproject.toml

Cherry picks of commits tested in #1768 to bring back hit line coverage

Coverage fix test

---

.github/ISSUE_TEMPLATE/01-bug-report.yml
CHANGELOG.md
src/aqua/version.py

[OP] Preparation for v0.13.5

---

.github/workflows/aqua-complete.yml
.github/workflows/aqua.yml
.github/workflows/create-fdb-container.yaml
dockerfiles/Dockerfile-development
dockerfiles/Dockerfile.ubuntu

This PR updates the docker base creation to eccodes 2.40. After container generation, workflow files need to be updated as well.

update base container to eccodes 2.40

---

CHANGELOG.md
config/styles/aqua.mplstyle
src/aqua/graphics/timeseries.py
src/aqua/graphics/util_timeseries.py

As per title, following the discussion in issue #1839 , some minor change to linewidths, xticks and bottom spine of the timeseris are implemented. 
Close #1839

Further graphical timeseries adjustments

---

.github/workflows/aqua-complete.yml
.github/workflows/aqua.yml
.github/workflows/create-fdb-container.yaml
CHANGELOG.md
dockerfiles/Dockerfile-development
dockerfiles/Dockerfile.ubuntu

Create a new base contaienr with fdb 5.15.11 according to the recent software stack upgrade on Lumi

update container 5.15

---

LICENSE
README.md

Update Readme and license

---

.github/workflows/aqua-complete.yml
.github/workflows/aqua.yml
CHANGELOG.md
src/aqua/cli/main.py
src/aqua/util/eccodes.py

Fix issue arising for too many requests to the ClimateDT catalog

Github authentication based on token for the catalog

---

src/aqua/lra_generator/lra_generator.py
src/aqua/reader/reader.py
tests/test_sci_tools.py

Fixing broken tests following #1861

fix aqua regridded

---

CHANGELOG.md
src/aqua/data_model/coordtranformer.py

Small fix to improve the logging and avoid a warning to arise.

improve logging of data_model

---

CHANGELOG.md
src/aqua_diagnostics/core/output_saver.py
tests/test_output-saver_NEW.py

Refine the OutputSaver as requested in #1900 
Close #1900
----

Outputsaver refinement

---

CHANGELOG.md
src/aqua/version.py

v0.16.0-alpha preparation

---

src/aqua/util/config.py

Lowering "no paths found in the machine configuration file" loglevel

---

.github/ISSUE_TEMPLATE/01-bug-report.yml
.github/PULL_REQUEST_TEMPLATE/standard_pull_request.md

As needed by the v0.13.6 release, I'm updating the issue tab

Update issue for v0.13.6 release

---

src/aqua_diagnostics/core/diagnostic.py

quick fix of typo in _set_region function of diagnostics.py

Fixing typo in _set_region function of diagnostics.py

---

src/aqua_diagnostics/ocean_drift/hovmoller.py

This PR is for `hovmoller.py` to adapt `select_region` from the `diagnostics.py`.

Update in hovmoller.py

---

.github/workflows/aqua.yml
CHANGELOG.md

Something seems to have changed and ECMWF credentials do not work anymore to access polytope, but the DESP key does.

No email in polytope secret

---

CHANGELOG.md
src/aqua/graphics/timeseries.py
src/aqua/graphics/util_timeseries.py
src/aqua_diagnostics/timeseries/plot_timeseries.py

As per title, now figure plot again same color for monthly and annual data.

Fix timeseries color

---

CHANGELOG.md
docs/sphinx/source/new_diagnostics/guidelines/output_management.rst
notebooks/diagnostics/ouputsaver.ipynb
src/aqua_diagnostics/core/output_saver.py

This PR adds documentation and a demonstrative notebook to the new OutputSaver class, currently missing.
Close #1996
Tag here relevant people to involve in the discussion:
----

Adding docs and notebook for the new OutputSaver

---

.github/workflows/create-fdb-container.yaml
CHANGELOG.md
dockerfiles/Dockerfile.ubuntu

Updates the versions, the container should be rebuilt
Close #2021
@oloapinivad @jhardenberg

Update ubuntu dockerfile for stack 7.0.2.8

---

CHANGELOG.md
config/diagnostics/timeseries/config_timeseries_atm.yaml
config/diagnostics/timeseries/config_timeseries_oce.yaml
src/aqua_diagnostics/timeseries/cli_timeseries.py

As per title, in order to temporary solve the issue in #2011 
cc @oloapinivad

Expose the `center_time` option in the timeseries cli

---

CHANGELOG.md
src/aqua/fixer/__init__.py
src/aqua/fixer/evaluate_formula.py
src/aqua/fixer/fixer.py
src/aqua/fixer/formula.py
src/aqua/util/__init__.py
src/aqua/util/yaml.py
src/aqua_diagnostics/timeseries/base.py
src/aqua_diagnostics/timeseries/gregory.py
tests/test_fixer.py

Replace the eval_formula function hidden in the util/yaml.py and move it as a slightly more flexible class in the Fixer module.
This allow to update the metadata of the data arrray according to the formula and increase the possibility to improve the evaluation with other operations. I did not touch the internal evaluation flow, just wrap it in a more flexible tool.
Idk if we now want documentation on this, I don't think so, it's fine more exposed in the API.
Close #2026
@oloapinivad

Evaluate formula class

---

CHANGELOG.md
docs/sphinx/source/other_components.rst
src/aqua/reader/reader.py
src/aqua/timstat/timstat.py
tests/test_timstat.py

As per title, simple expansion of the timstat module to support a sum operator. 
----

introducing timsum operator

---

CHANGELOG.md
src/aqua_diagnostics/timeseries/base.py
src/aqua_diagnostics/timeseries/plot_seasonalcycles.py
src/aqua_diagnostics/timeseries/plot_timeseries.py
src/aqua_diagnostics/timeseries/seasonalcycles.py
src/aqua_diagnostics/timeseries/timeseries.py
tests/timeseries/test_timeseries.py

The region is working being deduced by AQUA_region variable

Better management of regions in timeseries

---

CHANGELOG.md
docs/sphinx/source/graphics.rst

Update CHANGELOG and graphics documentation for get_projection() utility function
Mini-PR. Update docs and changelog; no relevant changes to the code.
Related to #2068

Update doc and changelog for get_projection

---

CHANGELOG.md
docs/sphinx/source/aqua_console.rst
src/aqua/cli/main.py
tests/test_console.py

Add `aqua update -c all` option and a better management of the github pat, that can be used both from the github workflow and a user
Close #1442
----

Console refinement

---

CHANGELOG.md
src/aqua/util/realizations.py
tests/test_util.py

There was an issue with integer realization, making the LRA for realization fail. Fixed here
Close #2064 
cc @oloapinivad

Fix format_realization for int argument

---

CHANGELOG.md
src/aqua/data_model/coordtranformer.py

This is an (AI generated) solution for the seaice unit conversion problem for coordinates (#2132).
If an incompatible conversion is requested it skips it with a warning .... looks ok to me.
Close #2132 
----

Fix incompatible coordinate transformations

---

CHANGELOG.md
config/analysis/config.aqua-analysis.yaml

This updates the `aqua-analysis` config script to use the new seaice diagnostics plus some cleanup
Relevant for #2124 
----

Update aqua-analysis config for new seaice and cleanup

---

CHANGELOG.md
src/aqua_diagnostics/timeseries/plot_gregory.py

Follow the #TODO comment to avoid Try/Except with a small refactoring.

[Gregory plot] Small change to avoid try-except in set_label

---

CHANGELOG.md
src/aqua/cli/diagnostic_config.py

Quick fix of seaice diagnostic config file path for aqua install.
Close #2164

[Seaice] Fix aqua install config file path

---

CHANGELOG.md
src/aqua/cli/catgen.py

Fix bug in catgen: monthly chunking for monthly data
Close #2167 
Tag here relevant people to involve in the discussion:
@mbatllem @mnurisso 

Hotfix catgen

---

CHANGELOG.md
config/fixes/EC-EARTH4.yaml
config/fixes/default.yaml
config/grids/EC-EARTH4.yaml

This implements a few minor fixes which allow running analysis on EC-Earth4 data
@mnurisso 
----

Minor EC-Earth related fixes

---

.github/workflows/aqua-complete.yml
.github/workflows/aqua.yml

action update to enable dependabot tests

---

src/aqua_diagnostics/seaice/plot_seaice.py
src/aqua_diagnostics/seaice/seaice.py

Following error raised in [AQUA-Run](https://github.com/DestinE-Climate-DT/AQUA/actions/runs/17481807234/job/49653363664#step:11:27), this PR aim to fix any compatibility issue with older Python versions (e.g. 3.10, 3.11)

Fix quotation mark issue in f-string with older python versions

---

config/diagnostics/radiation/config_radiation-timeseries.yaml
config/diagnostics/timeseries/config_timeseries_atm.yaml

As per title,setting berkely in gregory in radiation configuration file

change berkeley in gregory

---

src/aqua_diagnostics/seaice/plot_2d_seaice.py

Adjust timestamp in seaice bias descriptions.
Close #2275

[Seaice] adjust timestamp dates in bias description

---

src/aqua_diagnostics/teleconnections/plot_nao.py

Fix NAO title

---

CHANGELOG.md
src/aqua/graphics/__init__.py
src/aqua/graphics/vertical_line.py

Close #issue_number
Tag here relevant people to involve in the discussion:
----

Vertical line single plot function

---

CHANGELOG.md
src/aqua_diagnostics/timeseries/base.py

Adjust timeseries and seasonal cycles title and description

---

config/diagnostics/seaice/config_seaice.yaml
config/grids/observations.yaml

This is the last step for the upgrade of the OSI-SAF, replacing the old dataset with the new one.
To avoid feature breaking in diagnostics, it has to be merged together with https://github.com/DestinE-Climate-DT/Climate-DT-catalog/pull/185
@tovaz92

replace osi saf with new aqua dataset
