- CHANGELOG.md
- cli/aqua-web/push_s3.py
This hotfix restores compatibility with boto3 >= 1.36.0.
`push_s3.py` had stopped working after recent environment updates, throwing this error message:
```
Error uploading file: Failed to upload /users/jvonhar/test.txt to aquatest2/test.txt: An error occurred (XAmzContentSHA256Mismatch) when c
alling the PutObject operation: None
```
The problem started with boto3 version >= 1.36.0, earlier versions worked.
This solution is better than a pin, since it fixes the issue both with recent and older versions of boto3.
We will probably need to fix this also in 0.13-operational if we plan to push future op figures to the dashboard.
----
> Hotfix: push_s3 compatibility with boto3>=1.36.0

- CHANGELOG.md
- tests/test_catgen.py
The latest version of the Data Portfolio includes a different number of sources for ICON, causing our tests to fail. Therefore, I am adapting here the Catgen test.
> Hotfix to catgen test

- CHANGELOG.md
- src/aqua/lra_generator/lra_generator.py
- tests/test_lra.py
Enable LRA compression also for concat yearly files, which was missing. I would not applicate this to operational.
> LRA zip compression for yearly files

- .github/workflows/aqua.yml
- CHANGELOG.md
- src/aqua/cli/main.py
- tests/test_catgen.py
Enable tests for the operational branch and remove the climatedt token which is not necessary anymore and disabled now.
> [OP] Enable tests for v0.13-operational

- .github/ISSUE_TEMPLATE/01-bug-report.yml
- CHANGELOG.md
- pyproject.toml
> [OP] 0.13.2 preparation

- CHANGELOG.md
- config/catgen/production.j2
- config/catgen/reduced.j2
Solution for #1740 
Changes the fixer_name block if-else using instead a default backfall value
Close #1740
> [OP] Changing if statement for fixer_name in catgen

- CHANGELOG.md
- docs/sphinx/source/diagnostics/guidelines/default_parser.rst
- docs/sphinx/source/diagnostics/index.rst
- src/aqua_diagnostics/core/util.py
- tests/diagnostic_core/test_core_util.py
Add to the default parser:
- `--regrid` to enable `r100` regrid
- `--nworkers`, `-n` to set the workers number
- `--cluster` to store an already open cluster
- `--outputdir` to specify directory for output
Close #1713
> Add additional command-line arguments for configuration and processing options

- .github/dependabot.yml
- .github/workflows/aqua.yml
- CHANGELOG.md
This  - in theory - should allow for more precise label-triggering actions as well as action to be triggered when dependenabot is set up.
> More flexible action including also Dependabot case

- CHANGELOG.md
- src/aqua/gsv/intake_gsv.py
- tests/test_gsv.py
This PR is only to start working and discussing on a solution towards the continued problems discussed in #1715 
In this branch I keep the previous structure which instantiates a new GSVRetriever object the first time or every time `FDB_HOME` changes, but additionally it also instantiates a new object anyway  (as in older versions of AQUA) before running the retrieve. This means that the first time this is run two gsv objects are instantiated and again, two are instantiated if `FDB_HOME` changes. 
Apparently this allows the code to run again correctly both on bridge and hpc and avoids the 'infinite hang' issue. Basically it implements the first solution discussed at the top of #1715 where it was found that instantiating GSVRetriever twice seemed to solve the problem.  Of course the issue …
> Further intake-gsv fixes

- .github/ISSUE_TEMPLATE/01-bug-report.yml
- CHANGELOG.md
- src/aqua/version.py
> v0.13.3 prepare

- CHANGELOG.md
- docs/sphinx/source/adding_data.rst
- src/aqua/gsv/intake_gsv.py
- tests/catgen/fdb_info_hpc-only.yaml
- tests/test_gsv.py
The intake GSV can now load as well a fdb_info_file which contains only the data block, as it will be as long as something is transferred on the bridge.
Only in that moment the bridge block will be added by the workflow.
Close #1760
> [OP] Intake GSV can now handle fdb_info_file with only the data block

- .github/ISSUE_TEMPLATE/01-bug-report.yml
- CHANGELOG.md
- src/aqua/version.py
> Version to v0.13.4

- CHANGELOG.md
- src/aqua/graphics/timeseries.py
- src/aqua_diagnostics/timeseries/timeseries.py
With @jhardenberg we noticed that the timeseries plot appearing in the aqua explorer has ylabel missing in some plot.
Despite the initial idea of a possible bug in the plot layout, this is rather a case in which data for timeseries are badly formatted and plot_timeseries do not manage to find a common ylabel for the plot.
The PR introduces an handling of this case, in which an ylabel is evaluated and used only if matplotlib fails in finding one.
Since the timeseries are being refactored in #1712 and the plot routine in #1729 I propose to introduce this solution only in the operational branch and do not apply any bugfix in the main branch.
> [Op] Fix timeseries ylabel

- .github/workflows/aqua-complete.yml
- CHANGELOG.md
- docs/sphinx/source/adding_data.rst
- pyproject.toml
- src/aqua/reader/reader.py
- tests/test_basic.py
xarray v2025.01.2 introduced the possibility to ask for non nanosecond precision when opening a dataset.
The PR introduces the possibility to use this info in the catalog metadata, so that we can open with catalog-specified precision
> Add support for custom time decoding for intake driver in Reader class

- CHANGELOG.md
- src/aqua_diagnostics/core/diagnostic.py
Sometimes it can be useful to return data from a retrieve instead of updating the self.data
This PR introduces such update for the Diagnostic primitive class.
> retrieve method for Diagnostic class can return data

- CHANGELOG.md
- config/diagnostics/global_biases/config_global_biases.yaml
- diagnostics/ocean3d/cli/cli_ocean3d.py
- docs/sphinx/source/diagnostics/atm_global_mean.rst
- docs/sphinx/source/diagnostics/ocean3d.rst
- docs/sphinx/source/diagnostics/teleconnections.rst
- src/aqua_diagnostics/cli/cli_checker.py
- src/aqua_diagnostics/core/util.py
- src/aqua_diagnostics/global_biases/cli_global_biases.py
- src/aqua_diagnostics/teleconnections/cli_teleconnections.py
This adds a `--regrid <target>` option to several relevant diagnostics which were missing it.
The logic is always that this is optional and it overrides the config file if provided. 
The upgraded diagnostics are:
- global_biases
- teleconnections
- ocean3d
- cli_checker
Please notice that seaice diagnostics already had this capability.
----
> Add regrid option to relevant diagnostic cli

- CHANGELOG.md
- src/aqua_diagnostics/core/__init__.py
- src/aqua_diagnostics/core/util.py
- tests/diagnostic_core/test_core_util.py
I introduce a conver_data() function in the diagnostic utilities in order to convert data from one unit to another one, taking a dataset/dataarray and modifying only the requested variable. It also update the history attribute as the Reader does for data provenance.
> `convert_data()` as diagnostics core utility function

- CHANGELOG.md
- config/grids/ICON.yaml
Adding missing yaml blocks for R02B08 ICON oceanic grid healpix zoom 7 for the operational release
> [OP] Healpix 7 grids for R02B08 ICON

- CHANGELOG.md
- config/fixes/convention-eccodes.yaml
Add some cmor sources to `convention-eccodes.yaml` which were missing.
This also fixes a wrong grib code discussed in #1798 
Close #1798
----
> Fix tcc grib code and add cmor sources to the convention file

- .github/ISSUE_TEMPLATE/01-bug-report.yml
- CHANGELOG.md
- src/aqua/version.py
> Preparation v0.14.0

- CHANGELOG.md
- dockerfiles/Dockerfile-development
Since ubuntu 24.04 the GID is set to 1000 by default in the container. We then update the dockerfile to set GID only if this is not defined yet.
> Check if GID exists before adding group in Dockerfile-development

- .github/workflows/aqua.yml
- src/aqua/version.py
Catgen cannot be tested and it is not working due to #1840 
Since an update is necessary we temporarily disable the catgen tests.
Also we update the version to 0.14.1-alpha to follow the strategy of always having the target version in the main
> Temp catgen disable

- docs/sphinx/source/dashboard.rst
The script was already removed, here I'm cleaning just the documentation
Close #1875
> Remove outdated documentation on make_push_docs.sh

- .github/workflows/aqua.yml
- codecov.yml
fixes https://github.com/codecov/feedback/issues/663
I'm not 100% sure this will be the right fix, but I feel good that this is what needs to happen. 
> [!WARNING]
> One note, I suspect something weird is going on with getting the `git` tree and it's defaulting to our backup file searcher. I would suggest running `git ls-files` before this command to double-check that it is doing so
Close #issue_number
----
> fix: update Codecov paths

- CHANGELOG.md
- docs/sphinx/source/lra.rst
- src/aqua/cli/lra.py
- src/aqua/lra_generator/lra_generator.py
- src/aqua/util/sci_util.py
- tests/test_console.py
- tests/test_lra.py
This expands LRA capabilities to compute also additional statistics, not only the mean.
It contains also some other minor improvements to LRA functionality, in particular grouping annual files using cdo (which is significantly faster than using xarray). 
Close #1885
----
> Expand LRA to compute also other statistics and some other refinements

- CHANGELOG.md
- cli/aqua-web/make_contents.py
Somehow the version of `make_content.py` was never updated and did not accept the `-c` option, despite `push_analysis.sh` expecting it.
Close #1898 
----
> [OP] Hotfix for push_analysis not finding config file

- .github/workflows/aqua.yml
- CHANGELOG.md
- docs/sphinx/source/advanced_topics.rst
- src/aqua/gsv/intake_gsv.py
- src/aqua/reader/reader.py
- src/aqua/util/config.py
- tests/test_catalog.py
- tests/test_gsv.py
This adds polytope support with the new `engine` keyword (can be 'fdb' (default) or 'polytope'). The keyword can either be added to a catalog entry or be specified directly in the reader (it exploits the fact that the kwargs are passed directly to intake).
To be tested for speed and if remote functionality really works well. Please notice that the current implementation in the GSVRetriever uses a temporary grib file on disk for each message, so it has to be seen if this is ok in terms of speed.
The user will need credentials to access polytope. To this end get polytope credentials and create a `~/.polytopeapirc` file in your home with this content:
```
{
"user_email" : "<your.mail>",
"user_key" : "<your.key>"
}
```
I will add also some info on this in the docs.
Close #1534 
----
> Polytope support

- CHANGELOG.md
- src/aqua/graphics/multiple_maps.py
This PR updates the colorbar to use scientific notation in multiiple maps plots, preventing label overlap when very small values are present (e.g., in seasonal plots for the GlobalBiases diagnostic).
Close #1952
----
> Scientific notation in cbar in multiple maps plots

- .github/ISSUE_TEMPLATE/01-bug-report.yml
- .github/workflows/aqua.yml
- CHANGELOG.md
- environment.yml
- src/aqua/cli/main.py
- src/aqua/version.py
> Preparation to v0.13.6

- .gitignore
- CHANGELOG.md
- download_data_for_tests.sh
- environment.yml
Due to the recent changes in CDO #1971 we're trying to accomodate the missing attributes in the file needed for test with an update of the tests tar.gz on swift.
The PR is updating the download link used in tests and generalizing the gitignore file so that no further modifications of it will be needed for tests.
Close #1971 (if we remove the CDO pin in this PR as well)
cc @oloapinivad
> Test file update (v6)

- CHANGELOG.md
- src/aqua/reader/reader.py
- src/aqua_diagnostics/core/diagnostic.py
During testing, I noticed that the retrieve() method does not raise an error when an empty dataset is returned—for example, when a non-existent variable name is requested.
> Raise an error if retrieve() in core diagnostic returns an empty dataset

- CHANGELOG.md
- pyproject.toml
Removing the hard pin to the h5py installation, which is breaking the test, in favor of a softer lower version limit.
HDF5 is kept explicit in the environment file, while the h5py is now installed trough the available pipy package.
Close #2001
cc @jhardenberg if you agree with the modification I'd merge it (once tests are done) in order to keep the tests working in the other branches.
> Update h5py dependency to avoid broken test and increase environment flexibility

- src/aqua_diagnostics/core/util.py
- src/aqua_diagnostics/global_biases/cli_global_biases.py
- src/aqua_diagnostics/teleconnections/cli_teleconnections.py
- src/aqua_diagnostics/timeseries/cli_timeseries.py
- tests/diagnostic_core/test_core_util.py
Small change, to be tested, so that `load_diagnostic_config` does not receive a generic args but rather a specific configuration file to be loaded. I am pretty sure it is going to break if config has no default.
> Refactor `load_diagnostic_config` to load multiple configuration files

- .github/ISSUE_TEMPLATE/01-bug-report.yml
- CHANGELOG.md
- src/aqua/version.py
> Preparation to release 0.16

- CHANGELOG.md
- src/aqua/util/__init__.py
- src/aqua/util/graphics.py
- src/aqua_diagnostics/teleconnections/plot_nao.py
This PR introduces the modularization of the function that enables switching the axes box from a square to a circular shape. This enhancement improves visualization for specific map projections where a circular domain is more appropriate, such as polar stereographic views.
Close #2099 
----
> modularise function for circular boundary to cartopy geoaxes

- CHANGELOG.md
- src/aqua/graphics/gridlines.py
- src/aqua/graphics/single_map.py
- tests/test_graphics.py
This PR aims to reintroduce gridlines in plot_single_map.py, with a focus on maximizing flexibility while maintaining a sensible approach given the potential visualization issues associated with different map projections. The original functionalities remain unchanged; this is simply an optional extension to enhance visualization capabilities.
Close #2104 
----
> Add gridline option to plot_single_map

- CHANGELOG.md
- diagnostics/seaice/seaice/seaice_class.py
This fixes the seaice volume and extend diagnostics which are currently failing as described in #2110
Indeed these diagnostics accumulated a quite impressive collection of bugs. The main one is their reference to a now not supported `grid_area` reader class property (we have only `src_grid_area` and `tgt_grid_area`). 
Then there were some issues with plotting and Dataset shapes (more mysterious where these come from)
Btw: I noticed that the reader initializes `grid_area` to Null but then never changes it again. Should we support it or remove it entirely?
Close #2110 
Relevant for #2103 
----
> Fix legacy seaice extent and volume diagnostics

- CHANGELOG.md
- config/diagnostics/seaice/config_seaice.yaml
- src/aqua_diagnostics/core/util.py
- src/aqua_diagnostics/seaice/cli_seaice.py
- src/aqua_diagnostics/seaice/plot_2d_seaice.py
- src/aqua_diagnostics/seaice/plot_seaice.py
- src/aqua_diagnostics/seaice/seaice.py
- tests/seaice/test_plot_2d_seaice.py
- tests/seaice/test_plot_seaice.py
This is an attempt to fix the output paths for the new seaice diagnostic.
Notice that the diagnostic was using the wrong `OutputSaver`  (the one in `aqua.util` instead of the one in `aqua.diagnostics.core`).
Close #2138 
----
> Adjust seaice paths and other details

- CHANGELOG.md
- src/aqua/fldstat/fldstat.py
This is a simpler patch for fldstat addressing the problem in #2120. The real problem is that for some reason we encounter a grid area file which has an additional singleton 'time' coordinate, so the coordinates in `align_area_coordinates()` are not only lon and lat as expected. In a more general refactor we may wish to make this more robust, but for now this works and diagnostic radiation-timeseries works. 
The alternative which I discussed in #2120 (dropping coordinates which are not also dimensions when reading the grid areas) also works but I am not sure if it may not fail in some more general cases ... so I would stick with this simpler patch for now.
Close #2120 
Close #2103
----
> fldstat fix for radiation timeseries

- CHANGELOG.md
- src/aqua/regridder/regridder.py
This solves a  problem which may arise  when a cellarea file is provided. Method `_generate_area()` in the Regridder class will then return a Dataarray, but actually our default is to have areas as Datasets (smmregrid returns datasets): at line 196 of `reader.py` we have `cell_area = self.src_grid_area.cell_area if areas else None` ... so that would fail if `self.src_grid_area` is a Dataarray.
----
> Areas should be a dataset

- CHANGELOG.md
- src/aqua/reader/reader.py
- src/aqua_diagnostics/core/diagnostic.py
- tests/seaice/test_seaice.py
- tests/test_basic.py
Fix: change #2141 by partially reverting the changes done. Using a `error` logging insead a `raise`.
Close #2168
> Show a logging error instead a raise for empty data reader retrival

- CHANGELOG.md
- config/diagnostics/radiation/config_radiation-timeseries.yaml
- config/diagnostics/timeseries/config_seasonalcycles_atm.yaml
- src/aqua_diagnostics/timeseries/cli_timeseries.py
The seasonalcycles diagnostic was not reading and passing the `center_time` option from the cli and this fixes that. 
Added explicit `center_time` keys also to the seasonal cycles and radiation config files which were missing it (completing #2028)
Linked to #2011
----
> [TimeSeries] Add missing center time option to seasonalcycles

- config/diagnostics/timeseries/config_timeseries_atm.yaml
- config/diagnostics/timeseries/config_timeseries_oce.yaml
As per title, this updates the configuration files to make use of two new datasets. 
----
> Update Gregory and oceanic timeseries to use BERKELEY-EARTH and ESA-CCI 
